# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import object.film as module_0
import object.actor as module_1


#Tools: Pynguin
#Random based sampling
# 39 test cases


def test_case_0():
    module_0.Film()


def test_case_1():
    str_0 = "b1"
    var_0 = module_0.Film(director=str_0, age_rating=str_0, comments=str_0)
    var_0.add_actor(str_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bytes_0 = b"W\xc5\xd4y\x9b\x9c4Y"
    module_0.searchMovies(bytes_0, bytes_0)


def test_case_3():
    film_0 = module_0.Film()
    film_0.set_name(film_0)
    film_0.add_actor(film_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = "b1"
    module_0.Film(str_0, str_0, genre=str_0)
    module_0.searchMovies(str_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    str_0 = "b1"
    module_0.Film(director=str_0, age_rating=str_0, ratings=str_0, description=str_0)
    module_0.searchMovies(str_0, str_0)


def test_case_6():
    film_0 = module_0.Film()
    film_0.get_cast()
    film_0.add_actor(film_0)


def test_case_7():
    film_0 = module_0.Film()
    film_0.add_actor(film_0)


def test_case_8():
    film_0 = module_0.Film()
    film_0.to_dict()


def test_case_9():
    film_0 = module_0.Film()
    var_0 = film_0.average_rating()
    assert var_0 == 0


def test_case_10():
    film_0 = module_0.Film()
    film_0.display_film()


def test_case_11():
    film_0 = module_0.Film()
    film_0.add_actor(film_0)
    film_0.set_cast(film_0)


def test_case_12():
    film_0 = module_0.Film()
    film_0.set_age_rating(film_0)
    film_0.add_actor(film_0)


@pytest.mark.xfail(strict=True)
def test_case_13():
    film_0 = module_0.Film()
    film_0.add_actor(film_0)
    film_0.add_actor(film_0)


def test_case_14():
    film_0 = module_0.Film()
    film_0.get_genre()


def test_case_15():
    none_type_0 = None
    film_0 = module_0.Film(
        cast=none_type_0, director=none_type_0, year=none_type_0, comments=none_type_0
    )
    film_0.set_producer(none_type_0)


def test_case_16():
    film_0 = module_0.Film()
    film_0.add_actor(film_0)
    film_0.get_producer()


def test_case_17():
    film_0 = module_0.Film()
    film_0.get_age_rating()
    film_0.display_film()


def test_case_18():
    film_0 = module_0.Film()
    film_0.set_year(film_0)
    film_0.to_dict()


def test_case_19():
    film_0 = module_0.Film()
    film_0.set_genre(film_0)
    film_0.add_actor(film_0)


def test_case_20():
    film_0 = module_0.Film()
    var_0 = film_0.add_actor(film_0)
    film_0.set_cast(var_0)


@pytest.mark.xfail(strict=True)
def test_case_21():
    film_0 = module_0.Film()
    var_0 = film_0.add_actor(film_0)
    film_0.set_genre(var_0)
    film_0.add_actor(film_0)


def test_case_22():
    none_type_0 = None
    film_0 = module_0.Film(
        cast=none_type_0, director=none_type_0, year=none_type_0, comments=none_type_0
    )
    film_0.get_name()


def test_case_23():
    film_0 = module_0.Film()
    film_0.display_film()


def test_case_24():
    film_0 = module_0.Film()
    film_0.get_director()
    film_0.display_film()


def test_case_25():
    film_0 = module_0.Film()
    var_0 = film_0.add_actor(film_0)
    film_0.set_director(var_0)


def test_case_26():
    film_0 = module_0.Film()
    var_0 = film_0.get_year()
    film_0.add_actor(var_0)


def test_case_27():
    film_0 = module_0.Film()
    film_0.to_dict()

@pytest.mark.xfail(reason="Pynguin generated invalid comment type (Film instead of Comment).")
def test_case_28():
    film_0 = module_0.Film()
    film_0.add_comment(film_0)
    film_0.to_dict()


@pytest.mark.xfail(strict=True)
def test_case_29():
    film_0 = module_0.Film()
    film_0.add_actor(film_0)
    film_0.display_film()


def test_case_30():
    bytes_0 = b""
    module_0.searchMovies(bytes_0, bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_31():
    bytes_0 = b"\xc0^if"
    film_0 = module_0.Film(
        bytes_0, producer=bytes_0, genre=bytes_0, age_rating=bytes_0, ratings=bytes_0
    )
    film_0.display_film()
    film_0.add_actor(bytes_0)
    actor_0 = module_1.Actor(bytes_0)
    tuple_0 = (actor_0, bytes_0, actor_0, actor_0)
    module_0.searchMovies(tuple_0, bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_32():
    film_0 = module_0.Film()
    film_0.add_comment(film_0)
    film_0.display_film()


@pytest.mark.xfail(strict=True)
def test_case_33():
    bytes_0 = b"\xa2"
    actor_0 = module_1.Actor(bytes_0, films=bytes_0)
    tuple_0 = (actor_0, bytes_0, actor_0, actor_0)
    module_0.searchMovies(tuple_0, bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_34():
    bytes_0 = b""
    actor_0 = module_1.Actor(bytes_0, films=bytes_0)
    tuple_0 = (actor_0, bytes_0, actor_0, actor_0)
    module_0.searchMovies(tuple_0, bytes_0)


def test_case_35():
    film_0 = module_0.Film()
    dict_0 = {film_0: film_0, film_0: film_0, film_0: film_0}
    str_0 = "P,"
    module_0.searchMovies(dict_0, str_0)


def test_case_36():
    film_0 = module_0.Film()
    actor_0 = module_1.Actor(films=film_0)
    film_0.add_actor(actor_0)
    film_0.add_actor(actor_0)


def test_case_37():
    film_0 = module_0.Film()
    actor_0 = module_1.Actor(film_0)
    film_0.add_actor(actor_0)
    var_0 = film_0.add_actor(film_0)
    assert len(film_0.cast) == 2


@pytest.mark.xfail(strict=True)
def test_case_38():
    bytes_0 = b"\xc4\xbd\xc0^if"
    var_0 = module_0.Film(bytes_0, bytes_0, director=bytes_0, description=bytes_0)
    tuple_0 = (var_0, bytes_0, var_0, var_0)
    module_0.searchMovies(tuple_0, bytes_0)
