# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import logic.scraper as module_0


def test_case_0():
    str_0 = ""
    module_0.parse_movies(str_0)
